# Generated by Django 5.0.6 on 2024-06-27 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='level',
            field=models.IntegerField(choices=[(-1, 'Elija un nivel'), (1, 'Bajo'), (2, 'Medio'), (3, 'Mayor')], default=-1, verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loanStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ppe',
            name='idPpe',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tool',
            name='level',
            field=models.IntegerField(choices=[(-1, 'Elija un nivel'), (1, 'Bajo'), (2, 'Medio'), (3, 'Mayor')], default=-1, verbose_name='Nivel'),
        ),
    ]
